// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NotifySystem(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifySystem'](arg1, arg2, arg3);
}

export function PushExternalNotification(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PushExternalNotification'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function RevealWindow() {
  return window['go']['main']['App']['RevealWindow']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetTrayIcon(arg1) {
  return window['go']['main']['App']['SetTrayIcon'](arg1);
}

export function SetViewMode(arg1) {
  return window['go']['main']['App']['SetViewMode'](arg1);
}
