// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NotifySystem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PushExternalNotification(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function RequestQuit():Promise<void>;

export function RevealWindow():Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<boolean>;

export function SetTrayIcon(arg1:Array<number>):Promise<void>;

export function SetViewMode(arg1:string):Promise<void>;
